---
# Main tasks for common role
- name: Update system packages
  yum:
    name: "*"
    state: latest
    update_only: yes
  register: update_result
  tags: [system, update]
  
- name: Log system update results
  copy:
    dest: "{{ log_dir }}/system_update_{{ ansible_date_time.date }}.txt"
    content: "{{ update_result | to_nice_yaml }}"
  tags: [system, logs]
    
- name: Install required packages
  yum:
    name: "{{ required_packages }}"
    state: present
  register: packages_result
  tags: [system, packages]
  
- name: Add HashiCorp repository
  shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
  args:
    creates: /etc/yum.repos.d/hashicorp.repo
  tags: [system, hashicorp]
    
- name: Install Terraform
  yum:
    name: terraform
    state: present
  register: terraform_install
  tags: [system, terraform]
  
- name: Verify Terraform installation
  command: terraform version
  register: terraform_version
  changed_when: false
  tags: [system, terraform]
  
- name: Log Terraform installation
  copy:
    dest: "{{ log_dir }}/terraform_install_{{ ansible_date_time.date }}.txt"
    content: "{{ terraform_version.stdout }}"
  tags: [system, terraform, logs]

- name: Clone CloudMart repository
  git:
    repo: https://github.com/jrmreis/cloudmart.git
    dest: /home/ec2-user/cloudmart
    clone: yes
  become_user: "{{ ec2_username }}"
  register: git_clone
  tags: [system, git]

# Import utility scripts tasks
- import_tasks: utility_scripts.yml
  tags: [utility]
