# Check these tasks and make sure they use the container_info.exists check, not the old references
- name: Run backend container
  docker_container:
    name: "{{ backend_container_name }}"
    image: "{{ backend_image_name }}:{{ backend_image_tag }}"
    state: started
    restart_policy: unless-stopped
    ports:
      - "{{ backend_port }}:{{ backend_port }}"
    env_file: "{{ backend_dir }}/.env"
  when: not backend_container_info.exists  # Make sure this condition is correct
  become: yes
  tags: [application, docker, container]
