---
# Global vars
aws_region: "us-east-1"
cluster_name: "cloudmart"
ec2_username: "ec2-user"
log_dir: "/home/ec2-user/logs"

# AWS ECR repositories
# Use actual ECR repos from inventory but with better variable names
backend_ecr_repo: "445567090747.dkr.ecr.us-east-1.amazonaws.com/cloudmart-backend"
frontend_ecr_repo: "445567090747.dkr.ecr.us-east-1.amazonaws.com/cloudmart-frontend"

# Docker image names and tags
backend_image_name: "cloudmart-backend"
backend_image_tag: "latest" 
frontend_image_name: "cloudmart-frontend"
frontend_image_tag: "latest"

# App directories
app_dir: "/home/ec2-user/challenge-day2"
backend_dir: "{{ app_dir }}/backend"
frontend_dir: "{{ app_dir }}/frontend"
k8s_dir: "/home/ec2-user/k8s"
backend_service_name: "cloudmart-backend-service"

# Homol environment variables
# These could be overridden in environment-specific files
backend_replicas: 1  # Reduced for homol
frontend_replicas: 1 # Reduced for homol
k8s_resource_limits:
  cpu: "0.25"        # Reduced for homol
  memory: "256Mi"    # Reduced for homol
k8s_resource_requests:
  cpu: "0.1"         # Reduced for homol
  memory: "128Mi"    # Reduced for homol
