---
# Homol environment-specific variables
backend_replicas: 1
frontend_replicas: 1
k8s_resource_limits:
  cpu: "0.25"
  memory: "256Mi"
k8s_resource_requests:
  cpu: "0.1"
  memory: "128Mi"
eks_node_type: "t3.small"  # Smaller instance type for homol
eks_nodes: 1
