---
# cloudmart_setup.yml - Main playbook for CloudMart workstation setup
- name: Configure CloudMart Workstation
  hosts: all
  become: yes
  
  pre_tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
        timeout: 300
        
    - name: Gather EC2 facts
      setup:
        gather_subset: all
        
    - name: Create logs directory
      file:
        path: "{{ log_dir }}"
        state: directory
        owner: "{{ ec2_username }}"
        group: "{{ ec2_username }}"
        mode: '0755'
        
    - name: Create CloudMart logs directory
      file:
        path: /var/log/cloudmart
        state: directory
        mode: '0755'
        
    - name: Create master log file with system information
      template:
        src: "master_log.j2"
        dest: "{{ log_dir }}/master_{{ ansible_date_time.date }}.txt"
        owner: "{{ ec2_username }}"
        group: "{{ ec2_username }}"
        mode: '0644'
  
  roles:
    - common
    - docker
    - kubernetes
    - application
    - deployment
  
  post_tasks:
    - name: Final status check
      shell: |
        echo "Setup completed at $(date)" > /home/ec2-user/setup-complete.log
        echo "Docker container status:" >> /home/ec2-user/setup-complete.log
        docker ps >> /home/ec2-user/setup-complete.log
        echo "Kubernetes status:" >> /home/ec2-user/setup-complete.log
        kubectl get pods >> /home/ec2-user/setup-complete.log
      args:
        executable: /bin/bash
      register: final_status
      become_user: "{{ ec2_username }}"
      
    - name: Archive log files
      archive:
        path: "{{ log_dir }}"
        dest: "/home/ec2-user/logs-archive-{{ ansible_date_time.date }}.tar.gz"
        owner: "{{ ec2_username }}"
        group: "{{ ec2_username }}"
        format: gz
        
    - name: Final completion message
      debug:
        msg: "CloudMart setup completed successfully! Connect via SSH: ssh {{ ec2_username }}@{{ ansible_host }}"
