---
# CloudMart Infrastructure Deployment
# Ensure proper sequencing of playbooks

# Import your actual setup playbook instead of prerequisites.yml
- name: Setup infrastructure and prerequisites
  import_playbook: ../cloudmart_setup.yml
  tags: [setup]

# If you don't have separate playbooks, you can add wait tasks directly
- name: Verify control plane is fully initialized
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Wait for API server to be fully available
      uri:
        url: "https://localhost:6443/healthz"
        validate_certs: no
        return_content: yes
      register: api_health
      until: api_health.status == 200
      retries: 30
      delay: 10
      ignore_errors: yes
  tags: [kubernetes, master, verification]

# Add wait for network components
- name: Verify network components are running
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Wait for CoreDNS to be ready
      shell: kubectl get pods -n kube-system -l k8s-app=kube-dns -o jsonpath='{.items[*].status.phase}' | grep -v Running || echo "CoreDNS Ready"
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: coredns_status
      until: "'CoreDNS Ready' in coredns_status.stdout or 'Running' in coredns_status.stdout"
      retries: 30
      delay: 10
      ignore_errors: yes
  tags: [kubernetes, networking, verification]

# Add wait for all nodes
- name: Verify all nodes are ready
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Check if all nodes are ready
      shell: kubectl get nodes | grep NotReady || echo "All nodes ready"
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: nodes_status
      until: "'All nodes ready' in nodes_status.stdout"
      retries: 20
      delay: 15
      ignore_errors: yes
  tags: [kubernetes, verification]
