---
# docker_setup.yml - Tasks for Docker installation and configuration

- name: Install Docker
  yum:
    name: docker
    state: present
  register: docker_install
  
- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  register: docker_service
  
- name: Add ec2-user to docker group
  user:
    name: "{{ ec2_username | default('ec2-user') }}"
    groups: docker
    append: yes
  become: yes

- name: Set /var/run/docker.sock permissions
  file:
    path: /var/run/docker.sock
    mode: '0666'
  become: yes
  notify: restart docker

- name: Test Docker installation
  command: docker run hello-world
  register: docker_test
  changed_when: false
  
- name: Log Docker installation status
  copy:
    dest: "{{ log_dir }}/docker_install_{{ ansible_date_time.date }}.txt"
    content: |
      Docker Installation: Successful
      Docker Service: Running
      Docker Socket Permissions: 0666
      Docker Test: Hello World executed successfully
  become: yes
