---
# kubernetes_setup.yml - Tasks for installing EKS tools and setting up Kubernetes

- name: Install eksctl
  block:
    - name: Download eksctl
      get_url:
        url: "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_{{ ansible_system }}_amd64.tar.gz"
        dest: /tmp/eksctl.tar.gz
        mode: '0644'
      
    - name: Extract eksctl
      unarchive:
        src: /tmp/eksctl.tar.gz
        dest: /tmp
        remote_src: yes
      
    - name: Move eksctl to /usr/bin
      copy:
        src: /tmp/eksctl
        dest: /usr/bin/eksctl
        mode: '0755'
        remote_src: yes
        
    - name: Verify eksctl installation
      command: eksctl version
      register: eksctl_version
      changed_when: false
      
    - name: Log eksctl installation
      copy:
        dest: "{{ log_dir }}/eksctl_install_{{ ansible_date_time.date }}.txt"
        content: "{{ eksctl_version.stdout }}"

- name: Install kubectl
  block:
    - name: Download kubectl
      get_url:
        url: "https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.9/2020-11-02/bin/linux/amd64/kubectl"
        dest: /tmp/kubectl
        mode: '0755'
        
    - name: Create bin directory for ec2-user
      file:
        path: /home/ec2-user/bin
        state: directory
        owner: "{{ ec2_username }}"
        group: "{{ ec2_username }}"
        mode: '0755'
        
    - name: Copy kubectl to user bin directory
      copy:
        src: /tmp/kubectl
        dest: /home/ec2-user/bin/kubectl
        owner: "{{ ec2_username }}"
        group: "{{ ec2_username }}"
        mode: '0755'
        remote_src: yes
        
    - name: Link kubectl to system path
      file:
        src: /home/ec2-user/bin/kubectl
        dest: /usr/local/bin/kubectl
        state: link
        
    - name: Update bashrc with PATH
      lineinfile:
        path: /home/ec2-user/.bashrc
        line: 'export PATH=$PATH:$HOME/bin'
        state: present
        
    - name: Fix kubeconfig API version
      replace:
        path: /home/{{ ec2_username }}/.kube/config
        regexp: 'apiVersion: client.authentication.k8s.io/v1beta1'
        replace: 'apiVersion: client.authentication.k8s.io/v1alpha1'
      become: yes
      become_user: "{{ ec2_username }}"
      ignore_errors: yes  # In case the file doesn't exist yet
        
    - name: Verify kubectl installation
      command: /home/ec2-user/bin/kubectl version --short --client
      register: kubectl_version
      changed_when: false
      
    - name: Log kubectl installation
      copy:
        dest: "{{ log_dir }}/kubectl_install_{{ ansible_date_time.date }}.txt"
        content: "{{ kubectl_version.stdout }}"

- name: Install AWS IAM Authenticator
  block:
    - name: Download AWS IAM Authenticator
      get_url:
        url: "https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.6.2/aws-iam-authenticator_0.6.2_linux_amd64"
        dest: /tmp/aws-iam-authenticator
        mode: '0755'
        
    - name: Move AWS IAM Authenticator to bin directory
      copy:
        src: /tmp/aws-iam-authenticator
        dest: /home/ec2-user/bin/aws-iam-authenticator
        owner: "{{ ec2_username }}"
        group: "{{ ec2_username }}"
        mode: '0755'
        remote_src: yes
        
    - name: Verify AWS IAM Authenticator installation
      command: /home/ec2-user/bin/aws-iam-authenticator version
      register: authenticator_version
      changed_when: false
      become_user: "{{ ec2_username }}"
      
    - name: Log AWS IAM Authenticator installation
      copy:
        dest: "{{ log_dir }}/aws_iam_authenticator_install_{{ ansible_date_time.date }}.txt"
        content: "{{ authenticator_version.stdout }}"
        
- name: Authenticate with ECR
  shell: |
    # Get your AWS account ID
    AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
    # Define region
    AWS_REGION={{ aws_region | default('us-east-1') }}
    # Define ECR repository name
    ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    # Authenticate
    aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}
  args:
    executable: /bin/bash
  become_user: "{{ ec2_username | default('ec2-user') }}"
  register: ecr_auth
  
- name: Tag and push backend image to ECR
  shell: |
    # Get your AWS account ID
    AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
    # Define region
    AWS_REGION={{ aws_region | default('us-east-1') }}
    # Define ECR repository URL
    BACKEND_ECR_REPO="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/cloudmart-backend"
    # Tag and push
    docker tag cloudmart-backend:latest ${BACKEND_ECR_REPO}:latest
    docker push ${BACKEND_ECR_REPO}:latest
  args:
    executable: /bin/bash
  become_user: "{{ ec2_username | default('ec2-user') }}"
  register: backend_push
  
- name: Tag and push frontend image to ECR
  shell: |
    # Get your AWS account ID
    AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
    # Define region
    AWS_REGION={{ aws_region | default('us-east-1') }}
    # Define ECR repository URL
    FRONTEND_ECR_REPO="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/cloudmart-frontend"
    # Tag and push
    docker tag cloudmart-frontend:latest ${FRONTEND_ECR_REPO}:latest
    docker push ${FRONTEND_ECR_REPO}:latest
  args:
    executable: /bin/bash
  become_user: "{{ ec2_username | default('ec2-user') }}"
  register: frontend_push

- name: Create k8s directory
  file:
    path: /home/ec2-user/k8s
    state: directory
    owner: "{{ ec2_username }}"
    group: "{{ ec2_username }}"
    mode: '0755'
