---
# utility_scripts.yml - Tasks for creating utility scripts

- name: Create health check script
  template:
    src: templates/health-check.sh.j2
    dest: /home/ec2-user/health-check.sh
    owner: "{{ ec2_username }}"
    group: "{{ ec2_username }}"
    mode: '0755'
    
- name: Create cleanup script
  template:
    src: templates/cleanup-cloudmart.sh.j2
    dest: /home/ec2-user/cleanup-cloudmart.sh
    owner: "{{ ec2_username }}"
    group: "{{ ec2_username }}"
    mode: '0755'
    
- name: Create log-watch script
  template:
    src: templates/log-watch.sh.j2
    dest: /home/ec2-user/log-watch.sh
    owner: "{{ ec2_username }}"
    group: "{{ ec2_username }}"
    mode: '0755'

- name: Create container deployment script
  template:
    src: templates/deploy_containers.sh.j2
    dest: /home/ec2-user/deploy_containers.sh
    owner: "{{ ec2_username | default('ec2-user') }}"
    group: "{{ ec2_username | default('ec2-user') }}"
    mode: '0755'

 - name: Create upApp script
   template:
    src: templates/upApp.sh.j2
    dest: /home/ec2-user/upApp.sh
    owner: "{{ ec2_username | default('ec2-user') }}"
    group: "{{ ec2_username | default('ec2-user') }}"
    mode: '0755'
